spring:
  application:
    name: service-discovery-eureka

server:
  port: 8761

eureka:
  server:
    enableSelfPreservation: false # 本地调试环境下关闭自我保护机制
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
