server:
  port: 9411

spring:
  application:
    name: zipkin-service
  rabbitmq:
    host: 10.248.37.171
    port: 5672
    username: admin
    password: manulife
    virtual-host: MBPSCD
    queue: zipkin
