server:
  port: 8762
spring:
  application:
    name: eureka-server2
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    hostname: server2
  client:
    serviceUrl:
      defaultZone: http://server1:8761/eureka/

logging:
  level:
    com.netflix: DEBUG